import { GlobalContextProvider } from "./Context/store";
import Container1 from "../components/basic/organs/container-1";

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html>
      <head>
        <title>Kentoverse</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" type="image/x-icon" href="/favicon.ico"></link>
      </head>

      <body>
        <GlobalContextProvider>
          <Container1 bgcolor={"#063970"}>{children}</Container1>
        </GlobalContextProvider>
      </body>
    </html>
  );
}
