import Head from 'next/head'
import styles from '@/styles/Home.module.css'



export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" type="image/x-icon" href="/favicon.ico"></link>
      </Head>

      <main className={styles.main}>
        <div className={styles.description}>
        <h1>HEY</h1>
        </div>

        <div className={styles.center}>
         <h1>HEY</h1>
        </div>
      </main>
    </>
  )
}
